[package]
name = "mailgun"
version = "0.1.0"
authors = ["Roey Darwish Dror <roey.ghost@gmail.com>"]

[dependencies]
reqwest = "0.8.5"
serde = "1.0.43"
serde_derive = "1.0.43"
serde_json = "1.0.16"
derive_builder = "0.5.1"
error-chain = "0.11.0"
